# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.boot_timeout = 180
    
    config.vm.define "node-master" do |master|
      master.vm.network "private_network", ip: "192.168.50.2"
      master.vm.hostname = "node-master"

      # SSH provisioning
      master.vm.provision "ssh", type: "shell" do |s|
        s.path = "scripts/master/ssh.sh"
      end

      # Bootstrap provisioning
      master.vm.provision "bootstrap", type: "shell" do |s|
        s.path = "scripts/bootstrap.sh"
      end

      # Hadoop provisioning
      master.vm.provision "hadoop", type: "shell" do |s|
        s.path = "scripts/hadoop.sh"
      end

      # Spark provisioning
      master.vm.provision "spark", type: "shell" do |s|
        s.path = "scripts/master/spark.sh"
      end

      # master.vm.provision :shell do |s|
        # s.path = "python.sh"
      # end

      # Configure VM memory
      master.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.customize ["setextradata", :id, "VBoxInternal/CPUM/HostCPUID/80000006/edx", 0x02009140]
      end
    end

    (1..2).each do |i|
      config.vm.define "node#{i}" do |node|
        node.vm.network "private_network", ip: "192.168.50.#{i+2}"
        node.vm.hostname = "node#{i}"

        # SSH provisioning
        node.vm.provision "ssh", type: "shell" do |s|
          s.path = "scripts/worker/ssh.sh"
        end

        # Bootstrap provisioning
        node.vm.provision "bootstrap", type: "shell" do |s|
          s.path = "scripts/bootstrap.sh"
        end
        
        node.vm.provision "hadoop", type: "shell" do |s|
          s.path = "scripts/hadoop.sh"
        end

        # Configure VM memory
        node.vm.provider "virtualbox" do |vb|
          vb.memory = 4096
          vb.customize ["setextradata", :id, "VBoxInternal/CPUM/HostCPUID/80000006/edx", 0x02009140]
        end
      end
    end
  
  end
  